### ISSUE TITLE
Font and Background Color

### ISSUE THREAD

**Issue by shahzaib3311** [dab246/flutter_super_html_viewer#3]
We need to handle font and background color in the flutter app. It uses white background when we render this widget and I cannot see any property related to font color and background color. I can see a CSS tag property do let me know how we can change the font and background color in the flutter app.

Thanks

Shah

**Comment by dab246** [comment]
@shahzaib3311  IMO, there are 2 ways you can do it.
1. You can pass a `css` code into it. Eg:

```dart
final cssStyle = '''
<style>
@font-face {
    font-family: myFirstFont;
    src: url(sansation_bold.woff);
    font-weight: bold;
}

body {
    font-family: myFirstFont;
    background-color: black;
}
</style>
''';

HtmlContentViewer(
     htmlContent: '<p>Here is some text</p> ',
     customStyleCssTag: cssStyle
);
```

2. Attach directly in html content

```dart 
HtmlContentViewer(
     htmlContent: '<p style="background-color: black;font-family: myFirstFont;">Here is some text</p> '
);
```
